# Python crash course
(C) 2022, Pramod Parajuli

## Data types and operations

### String

In [1]:
str1 = 'Hello World!'

In [2]:
print( str1 )

Hello World!


String slicing. The same slicing technique works with lists as well.

In [3]:
print( str1[1:] )

ello World!


In [4]:
print( str1[:10] )

Hello Worl


In [5]:
print( str1[2:10] )

llo Worl


In [6]:
print( str1[-1] )

!


In [7]:
print( str1[2: -3] )

llo Wor


In [8]:
for char in str1:
    print(char)

H
e
l
l
o
 
W
o
r
l
d
!


In [9]:
print( str1 * 3 )

Hello World!Hello World!Hello World!


In [10]:
len( str1 )

12

In [11]:
'World' in str1

True

In [12]:
if 'World' in str1:
    print('Found')
else:
    print('Not found')

Found


In [13]:
char_list = list( enumerate( str1 ) )

In [14]:
char_list

[(0, 'H'),
 (1, 'e'),
 (2, 'l'),
 (3, 'l'),
 (4, 'o'),
 (5, ' '),
 (6, 'W'),
 (7, 'o'),
 (8, 'r'),
 (9, 'l'),
 (10, 'd'),
 (11, '!')]

Formatted strings

In [15]:
first_name = "Elton"
last_name = "John"

full_name1 = "{0} {1}".format(first_name, last_name)
print(full_name1)

full_name2 = f"{first_name} {last_name}"
print(full_name2)

Elton John
Elton John


In [16]:
str2 = 'How are you doing?'

In [17]:
print (str1 + str2)

Hello World!How are you doing?


In [18]:
print(str1, str2)

Hello World! How are you doing?


In [19]:
print("Binary representation: {0:b}".format(5))

Binary representation: 101


In [20]:
print("Floating number: {0:e}".format(15.22))

Floating number: 1.522000e+01


In [21]:
print("octal number", oct(5))
print("binary number", bin(5))
print("hexadecimal number", hex(5))

octal number 0o5
binary number 0b101
hexadecimal number 0x5


In [22]:
print("|{:<10}|{:^10}|{:^10}|{:>15}|".format('decimal','octal', 'binary', 'hexadecimal'))
print("|{:<10}|{:^10}|{:^10}|{:>15}|".format(str(10), str(oct(10)), str(bin(10)), str(hex(10)) ) )

|decimal   |  octal   |  binary  |    hexadecimal|
|10        |   0o12   |  0b1010  |            0xa|


### Numeric data types

In [23]:
a = 10 # integer

In [24]:
a**3

1000

In [25]:
b = 10.5 # float

In [26]:
c = 1 +2j  # complex number

In [27]:
c + 3

(4+2j)

In [28]:
0b10 + 0xA

12

In [29]:
int(1.3)

1

In [30]:
int('1')

1

In [31]:
complex('1+4j')

(1+4j)

In [32]:
(1.1 + 2.2) == 3.33

False

In [33]:
print(0.1)

0.1


In [34]:
from decimal import Decimal

print(Decimal(0.1))

0.1000000000000000055511151231257827021181583404541015625


In [35]:
from fractions import Fraction

print(Fraction(1.5))

print( Fraction(-3, 10) < 0 )

3/2
True


In [36]:
import math

print(math.pi)

print(math.exp(10))

print(math.factorial(6))

3.141592653589793
22026.465794806718
720


### Lists

#### Number lists

In [37]:
num_list = [5, 7, 10, -12, 10]

In [38]:
print(num_list[2])
print(num_list[-3])

10
10


In [39]:
for num in num_list:
    print(num)

5
7
10
-12
10


In [40]:
sum(num_list)

20

In [41]:
max(num_list)

10

In [42]:
min(num_list)

-12

In [43]:
def avg(num_list):
    return sum(num_list) / len(num_list)

In [44]:
avg(num_list)

4.0

In [45]:
from numpy import mean

mean(num_list)

4.0

In [46]:
for num in num_list:
    print( 2 ** num )

32
128
1024
0.000244140625
1024


In [47]:
print ( [ 2 ** x for x in num_list ] )

[32, 128, 1024, 0.000244140625, 1024]


In [48]:
print ( [ 2 ** x for x in num_list if x > 5 ] )

[128, 1024, 1024]


In [49]:
print ( [ 2 ** x for x in num_list if x % 2 == 1 ] )

[32, 128]


In [50]:
10 in num_list

True

In [51]:
8 in num_list

False

In [52]:
num_list.count(10)

2

#### String lists

In [53]:
str_list = ['hello', 'world']

In [54]:
for str in str_list:
    print(str)

hello
world


In [55]:
str_list[1] = 'you'

print(str_list)

['hello', 'you']


In [56]:
str_list.append('OK')

print(str_list)

['hello', 'you', 'OK']


In [57]:
str_list.extend(['yeah', 'fine'])

print(str_list)

['hello', 'you', 'OK', 'yeah', 'fine']


In [58]:
str_list2 = ['hi', 'there']

In [59]:
combined_list = zip(str_list, str_list2)

In [60]:
for items in combined_list:
    print(items)

('hello', 'hi')
('you', 'there')


In [61]:
print( str_list + str_list2)

['hello', 'you', 'OK', 'yeah', 'fine', 'hi', 'there']


In [62]:
str_list2.insert(1, 'guys')

print( str_list2 )

['hi', 'guys', 'there']


In [63]:
del str_list2[2]

print( str_list2 )

['hi', 'guys']


In [64]:
str_list.pop()

print( str_list )

['hello', 'you', 'OK', 'yeah']


In [65]:
str_list.clear()

print( str_list )

[]


In [66]:
str_list2.reverse()

print( str_list2 ) 

['guys', 'hi']


#### Nested lists

In [67]:
n_list = ["Hi there", [1, 2, 3]]

print(n_list[0][4])
print(n_list[1][1])

h
2


#### List of lists

In [68]:
list_of_lists = [ [1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]]

In [69]:
list_of_lists[0]

[1, 2, 3]

In [70]:
list_of_lists[0:1]

[[1, 2, 3]]

In [71]:
for l in list_of_lists:
    print(sum(l))

6
15
24


### Tuples

Tuples are immutable data structures i.e. their contents can not changed during runtime

In [72]:
t = (1, 'Hello world', (2, 3, 4))

for item in t:
    print(item)

1
Hello world
(2, 3, 4)


In [73]:
# unpacking
a, b, c = t

print( a )
print( b )
print( c )

1
Hello world
(2, 3, 4)


In [74]:
# parentheses are not necessary to define a tuple

tuple1 = 1, 2
tuple2 = 1,


print( type(tuple1) )
print( type(tuple2) )

<class 'tuple'>
<class 'tuple'>


Indexes, negative index, slicing, merge, multiplication, membership test, iterations work with tuples same as lists.

### Sets

Sets are not indexed. Therefore, ordering of the items is not guaranteed.

In [75]:
s = {1, 'Hello world', (2, 3, 4)}

for item in s:
    print(item)

1
Hello world
(2, 3, 4)


In [76]:
# sets can not have duplicates!

s1 = {1, 2, 2, 3}

print( s1 )

{1, 2, 3}


In [77]:
# sets are mutable but items inside a set must only be immutable items

s1 = {1, 2, (3, 4)}

print( s1 )

{1, 2, (3, 4)}


In [78]:
# this is not allowed as the list [3, 4] is mutable
# s2 = {1, 2, [3, 4]}

In [79]:
# empty set can not be created with {}, it indicates a dictionary. Therefore, use set() for empty set

new_set = set()

print( type(new_set) )

<class 'set'>


In [80]:
# add a single element
s1.add(5)
print( s1 )


# add multiple elements
s1.update([6, 7, 8])
print( s1 )

{1, 2, 5, (3, 4)}
{1, 2, 5, (3, 4), 6, 7, 8}


In [81]:
# removing elements
s1.remove(6)
print( s1 )


{1, 2, 5, (3, 4), 7, 8}


Set operations

In [82]:
s2 = {1, 2, 9, 10}

# for union, use '|' operator
s1 | s2

s1.union(s2)

s2.union(s1)

{(3, 4), 1, 10, 2, 5, 7, 8, 9}

In [83]:
# for intersection, use '&' operator

s1 & s2

s1.intersection(s2)

s2.intersection(s1)

{1, 2}

In [84]:
# for set difference, use '-' operator
s1 - s2
s1.difference(s2)

s2 - s1
s2.difference(s1)

{9, 10}

In [85]:
# symmetric difference, use '^' operator

s1 ^ s2

s1.symmetric_difference(s2)

{(3, 4), 10, 5, 7, 8, 9}

### Dictionary

A dictionary is a key-value data structure

In [86]:
dict = {'fname': 'Elton', 'lname':'John'}

Normally, the key is used as index

In [87]:
for key in dict:
    print(key)

fname
lname


To obtain value, use key

In [88]:
for key in dict:
    print( dict[key])

Elton
John


In [89]:
for key in dict:
    print( dict.get(key))

Elton
John


In [90]:
dict['album'] = 'Captain and the Kid'

print( dict )

{'fname': 'Elton', 'lname': 'John', 'album': 'Captain and the Kid'}


In [91]:
marks = {}.fromkeys(['Math', 'English', 'Science'], 0)

print( marks )

{'Math': 0, 'English': 0, 'Science': 0}


In [92]:
square_values = {x : x*x for x in range(5)}

print( square_values )

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}


All objects can be deleted with del <objectname>

## Control flow

### if-else

In [106]:
i = 10
j =13
k = 9

if i > j:
    print("i is greater")
else:
    print("j is greater")

j is greater


In [107]:
if i > j:
    if i > k:
        print("i is largest number")
    elif k > i:
        print("k is largest number")
else:
    if j > k:
        print("j is largest number")
    else:
        print("k is largest number")

j is largest number


### for loop

In [108]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [110]:
for i in range(6, 16):
    print(i)

6
7
8
9
10
11
12
13
14
15


In [111]:
# at the end of for loop

for i in range(5):
    print(i)
else:
    print("Count over!")

0
1
2
3
4
Count over!


### while loop

In [115]:
counter = 1

while counter <= 10:
    print(counter)
    counter += 1


sum = 0
counter = 1

while counter <= 10:
    sum += counter
    counter += 1

print('The sum is: ', sum)

1
2
3
4
5
6
7
8
9
10
The sum is:  55


## Regular expressions

In [117]:
import re

# define a pattern that starts with C and ends with M 
pattern = '^C..M$'

str = 'CGIMites'

result = re.match(pattern, str)

if result:
    print("Match found")
else:
    print("Match not found")

Match not found


In [118]:
import re

# find numbers
pattern = '\d+'

str = 'Adam had 5 apples. He 4 of them to Eve. How he has only 1 apple left.'

result = re.findall(pattern, str)

print(result)

['5', '4', '1']


In [126]:
import re

# find all numbers 
pattern = '[0-9]+'

str = 'The budget is deficit by 11 % and total value was 845 millions. The affected population was 65039 .'

result = re.findall(pattern, str)

print(result)

['11', '845', '65039']


## Functions

Functions can return multiple values!

In [131]:
def min_max(lst):
    return min(lst), max(lst)

my_list = [3, 6, 1, 9, 2]

min_max(my_list)

(1, 9)

## Object oriented programming

In [138]:
class Person:
    def __init__(self, fname, mname, lname):
        self.first_name = fname
        self.middle_name = mname
        self.last_name = lname
    
    def fullname(self):
        return self.first_name + self.middle_name + self.last_name
    
    def set_first_name(self, fname):
        self.first_name = fname
        
p1 = Person('Pramod', '', 'Parajuli')
p1.fullname()

p1.set_first_name("Ram")
p1.fullname()

'RamParajuli'

## Using libraries

In [140]:
import numpy as np

mat_a = [2, 3, 4]
mat_b = [ [5, 6],
        [7, 8],
        [9, 1]]

np.matmul(mat_a, mat_b)


array([67, 40])

In [141]:
import numpy as np

mat_a = [2, 3, 4]
mat_b = [ [5, 6, 1],
        [7, 8, 3],
        [9, 1, 2]]

np.matmul(mat_a, mat_b)

array([67, 40, 19])

In [143]:
import numpy as np

mat_a = [2, 3, 4]
mat_b = [ [5, 6],
        [7, 8],
        [9, 1]]

np.matmul(mat_a, mat_b)

array([67, 40])

In [144]:
import numpy as np

mat_a = [[2, 3, 4],
         [11, 12, 13]]
mat_b = [ [5, 6],
        [7, 8],
        [9, 1]]

np.matmul(mat_a, mat_b)

array([[ 67,  40],
       [256, 175]])

In [145]:
import numpy as np

mat_a = [[2, 3, 4],
         [11, 12, 13]]
mat_b = [ [5, 6],
        [7, 8],
        [9, 1]]

np.dot(mat_a, mat_b)

array([[ 67,  40],
       [256, 175]])

In [147]:
import numpy as np

mat_a = [2, 3, 4]
mat_b = [5, 6, 7]

np.dot(mat_a, mat_b)

56

## Dictionary

In [1]:
dict = {'fname':'Elton', 'lname':'John'}

In [2]:
dict

{'fname': 'Elton', 'lname': 'John'}

In [3]:
dict['fname']

'Elton'

In [4]:
for key in dict:
    print(key)

fname
lname


In [7]:
for key in dict:
    print( dict[key] )

Elton
John
Captain and the Kid


In [6]:
dict['album'] = 'Captain and the Kid'

In [9]:
marks = {}.fromkeys(['Math', 'English', 'Science'], 0)

In [10]:
marks

{'Math': 0, 'English': 0, 'Science': 0}

In [11]:
squares = {x : x*x for x in range(5) }

In [12]:
squares

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [15]:
if 3 < 4 and 4 > 5:
    print('true')

## Regular expressions

In [18]:
import re

pattern = '^C..M$'

str = 'CXYM'

result = re.match(pattern, str)

if result:
    print("Match found")
else:
    print("Match not found")

Match found


In [19]:
import re

pattern = '\d+'

str = 'Adam had 5 apples. He gave 4 to Eve. Now he has only 1 apple left.'

result = re.findall(pattern, str)

print(result)

['5', '4', '1']


In [20]:
import re

pattern = '[0-9]+'

str = 'The budget is deficit by 11 % and total value was 845 millions'

result = re.findall(pattern, str)

print( result )

['11', '845']


# Using library

In [21]:
import numpy as np

mat_a = [1, 2, 3]

mat_b = [[4, 5],
        [7, 8],
        [9, 1]]

np.matmul(mat_a, mat_b)

array([45, 24])

In [22]:
np.dot(mat_a, mat_b)

array([45, 24])

In [23]:
mat_b = [5, 6, 7]

In [24]:
np.dot(mat_a, mat_b)

38