Reference: https://scikit-learn.org/stable/modules/generated/sklearn.multiclass.OneVsOneClassifier.html

In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [3]:
# obtain IRIS data

iris = datasets.load_iris()
X = iris.data
y = iris.target

X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [4]:
# Standardize the data, not essential. Use if liblinear fails to converge

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X)

print(scaler.mean_)

X = scaler.transform(X)

X[:5]

[5.84333333 3.05733333 3.758      1.19933333]


array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

In [5]:
# split data for training and testing
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.33,
                                                    shuffle=True)

In [6]:
# Pairwise classifier (one vs one classifier)

from sklearn.multiclass import OneVsOneClassifier
from sklearn.svm import LinearSVC

clf = OneVsOneClassifier(LinearSVC())

In [7]:
# train
model = clf.fit(X_train, y_train)

In [8]:
# Use the model/predictor to predict
y_pred = model.predict(X_test)

In [10]:
# view the accuracy
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.98


In [11]:
import numpy as np
from sklearn.model_selection import cross_val_score

cross_val_result = cross_val_score(clf, X, y, cv=4)

print("Cross validation scores", cross_val_result)
print("Average accuracy", np.mean(cross_val_result))

Cross validation scores [1.         0.97368421 0.94594595 1.        ]
Average accuracy 0.9799075391180655
