# TensorFlow basics

In [1]:
import tensorflow as tf
print("Tensorflow version:", tf.__version__)

Tensorflow version: 2.11.0


## Preparing the dataset

In [10]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
target = iris.target

print(X[:5])
print(target[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


## Encoding target values with OneHotEncoding

In [11]:
from sklearn.preprocessing import OneHotEncoder

onehot_encoder=OneHotEncoder(sparse_output=False)

reshaped=target.reshape(len(target), 1)

Y=onehot_encoder.fit_transform(reshaped)

print(Y[1:10])

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


## Train-test data split

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

## Configuring the model

In [29]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
  ])
model

## Compile the model

In [30]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

## Train the model

In [32]:
model.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5511 - accuracy: 0.7200
Epoch 2/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5430 - accuracy: 0.7200
Epoch 3/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5319 - accuracy: 0.8100
Epoch 4/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5238 - accuracy: 0.7300
Epoch 5/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5124 - accuracy: 0.7500
Epoch 6/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5012 - accuracy: 0.8000
Epoch 7/100
10/10 [==============================] - 0s 2ms/step - loss: 0.4942 - accuracy: 0.7700
Epoch 8/100
10/10 [==============================] - 0s 2ms/step - loss: 0.4859 - accuracy: 0.8300
Epoch 9/100
10/10 [==============================] - 0s 3ms/step - loss: 0.4796 - accuracy: 0.8100
Epoch 10/100
10/10 [==============================] - 0s 3ms/step - loss: 0.4693 - accuracy: 0.8000
Epoch 11/

## Evaluation of the model with test data

In [33]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.21963363885879517
Test accuracy: 0.9599999785423279


## Predicting the output

In [34]:
y_pred = model.predict(X_test)
y_pred[:5]

2/2 [==============================] - 0s 6ms/step


array([[6.3505527e-06, 6.9760635e-02, 9.3023300e-01],
       [1.9980196e-03, 8.6927038e-01, 1.2873146e-01],
       [9.9935621e-01, 6.2934484e-04, 1.4376729e-05],
       [5.2642295e-06, 1.5468825e-01, 8.4530652e-01],
       [9.9812263e-01, 1.8198515e-03, 5.7447600e-05]], dtype=float32)

## Compare actual and predicted values

In [35]:
import numpy as np
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")

Actual: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1 1 1 2 0 2 0 0 1 2 2 2 2]
Predicted: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 2 0 2 2 1 0
 2 1 1 2 0 2 0 0 1 2 2 2 2]
