# Artificial neural network foundations

## Perceptron training using error-corrective learning

In [1]:
import numpy as np

### Functional output of a perceptron
$$y=\sum{x_i.w_i}$$

In [2]:
# let's define some functions for perceptron operations

# output function
def functional_output(inputs, weights):    
    return np.dot(inputs, weights)

In [3]:
functional_output([1, 2], [3, 4])

11

### Threshold activation function
$$f(y)=\begin{cases} 1,&  \text{if y} \ge \theta  \\ 0 , & \text{otherwise} \end{cases} $$


In [4]:
# threshold activation function
def activation_output(output, threshold):
    if output >= threshold:
        return 1
    else:
        return 0

In [5]:
activation_output(3, 1)

1

### Error
$$\begin{align} e & = g-f  \\ \text{where,  } &  \text{g is expected value} \\ & \text{f is threshold output} \end{align}$$

In [6]:
# error function

def error(activation, expected):
    
    assert len(activation) == len(expected), 'Dimensions of parameter lists do not match!'
    
    return np.subtract(expected, activation)

In [7]:
error([3, 2], [2, 1])

array([-1, -1])

### Learning new weights

$$\begin{align}\delta{w} & =x.e.\alpha \\ \text{where, } & \text{x is input} \\ & \text{e is the error} \\ & \alpha \text{ is learning rate} \end{align} $$

The weight then shall be updated as
$$w_t = w_{t-1} + \delta{w}$$

In [20]:
# update weight
def delta_weight(x, error, learning_rate):
    return x * error * learning_rate

In [21]:
weight = delta_weight(1, 2, 1)

### Neural network 

In [10]:
class SimpleNN:
      
    # A set of bias, x1, x2, class label
    training_data = np.array([[-1, 1, 1, 1],
                              [-1, 1, 0, 0],
                              [-1, 0, 1, 0],
                              [-1, 0, 0, 0]])

    # a set of random weights
    weights = np.array([0, 1, -1])

    #learning rate
    learning_rate = 1

    # threshold 
    threshold = 1
    
    # splitting input and output from training data
    input_data = training_data[:, [0, 1, 2]]

    desired_output = training_data[:, [3]].T[0]

In [12]:
snn = SimpleNN()

print("Training data", snn.training_data)
print("Weights", snn.weights)
print("Learning rate: ", snn.learning_rate)
print("Threshold", snn.threshold)
print("Input data", snn.input_data)
print("Desired output", snn.desired_output)

Training data [[-1  1  1  1]
 [-1  1  0  0]
 [-1  0  1  0]
 [-1  0  0  0]]
Weights [ 0  1 -1]
Learning rate:  1
Threshold 1
Input data [[-1  1  1]
 [-1  1  0]
 [-1  0  1]
 [-1  0  0]]
Desired output [1 0 0 0]


In [14]:
# A simple feed forward mechanism

y = np.array(functional_output(snn.input_data, snn.weights))

print(y)

[ 0  1 -1  0]


In [15]:
# activation output
fy = np.array([activation_output(o, snn.threshold) for o in y])

print(fy)

[0 1 0 0]


In [16]:
# training cycle

err = error(fy, snn.desired_output)

print(err)

[ 1 -1  0  0]


In [34]:
# preparing initial data for training
w = snn.weights

counter = 0
epoch = 1

# if output equals desired output, no need to train
while not np.array_equal(snn.desired_output, fy):
   
    print("Epoch", epoch)    
    print("weights          input       desired_output         actual_output   error     action")
    
    # in each epoch, iterate through all training data
    for x in snn.input_data:
        
        # feed-forward 
        y = np.array(functional_output(snn.input_data, w))
        
        fy = np.array([activation_output(o, snn.threshold) for o in y])
        
        err = error(fy, snn.desired_output)
        
        # check error for current iteration i.e. current set of inputs. 
        # Current set of inputs can be located by using index of current set i.e. counter % 4 since there are 4 sample data
        
        # If error is 0 then do nothing, iterate over
        if err[counter%4] == 0:
            print(w, "\t", x, "\t", snn.desired_output[counter%4], "\t\t\t", fy[counter%4], 
                  "\t\t", err[counter%4], "\t no change")
        else:
            # if there is some error, then update the weight
            print(w, "\t", x, "\t", snn.desired_output[counter%4], "\t\t\t", fy[counter%4], 
                  "\t\t", err[counter%4], "\t update weight") 
            w = w + delta_weight(err[counter%4], snn.learning_rate, snn.input_data[counter%4])
                               
        counter +=1 
    
    epoch += 1

# after finishing the training, let's feed-forward once and see the results
print("The final result and outcomes")
iter = 0
for x in snn.input_data:
        y = np.array(functional_output(snn.input_data, w))        
        fy = np.array([activation_output(o, snn.threshold) for o in y])        
        err = error(fy, snn.desired_output)
        
        if err[iter] == 0:
            print(w, "\t", x, "\t", snn.desired_output[iter], "\t\t\t", fy[iter], 
                  "\t\t", err[iter], "\t no change")
        else:
            print(w, "\t", x, "\t", snn.desired_output[iter], "\t\t\t", fy[iter], 
                  "\t\t", err[iter], "\t update weight") 
            w = w + update_weights(err[iter], snn.learning_rate, snn.input_data[iter])            
                   
        iter +=1         

Epoch 1
weights          input       desired_output         actual_output   error     action
[ 0  1 -1] 	 [-1  1  1] 	 1 			 0 		 1 	 update weight
[-1  2  0] 	 [-1  1  0] 	 0 			 1 		 -1 	 update weight
[0 1 0] 	 [-1  0  1] 	 0 			 0 		 0 	 no change
[0 1 0] 	 [-1  0  0] 	 0 			 0 		 0 	 no change
Epoch 2
weights          input       desired_output         actual_output   error     action
[0 1 0] 	 [-1  1  1] 	 1 			 1 		 0 	 no change
[0 1 0] 	 [-1  1  0] 	 0 			 1 		 -1 	 update weight
[1 0 0] 	 [-1  0  1] 	 0 			 0 		 0 	 no change
[1 0 0] 	 [-1  0  0] 	 0 			 0 		 0 	 no change
Epoch 3
weights          input       desired_output         actual_output   error     action
[1 0 0] 	 [-1  1  1] 	 1 			 0 		 1 	 update weight
[0 1 1] 	 [-1  1  0] 	 0 			 1 		 -1 	 update weight
[1 0 1] 	 [-1  0  1] 	 0 			 0 		 0 	 no change
[1 0 1] 	 [-1  0  0] 	 0 			 0 		 0 	 no change
Epoch 4
weights          input       desired_output         actual_output   error     action
[1 0 1] 	 [-1  1  1] 	 