# Matrix operations for image processing

In [1]:
import cv2

In [2]:
image = cv2.imread("sample.jpg")
print(image)
print("Size of the image: ", len(image), len(image[0]))

[[[187 181 176]
  [187 181 176]
  [187 181 176]
  ...
  [193 173 162]
  [185 167 156]
  [154 136 125]]

 [[187 181 176]
  [187 181 176]
  [187 181 176]
  ...
  [188 170 159]
  [115  96  88]
  [ 40  24  12]]

 [[186 180 175]
  [186 180 175]
  [186 180 175]
  ...
  [111  92  84]
  [ 52  34  27]
  [ 35  20  11]]

 ...

 [[ 90  91  89]
  [ 97  98  96]
  [104 105 103]
  ...
  [ 33  43  50]
  [ 33  43  50]
  [ 33  43  50]]

 [[ 85  86  84]
  [ 85  86  84]
  [ 82  83  81]
  ...
  [ 34  45  49]
  [ 34  45  49]
  [ 36  47  51]]

 [[ 99 100  98]
  [ 96  97  95]
  [ 90  91  89]
  ...
  [ 34  45  49]
  [ 34  45  49]
  [ 36  47  51]]]
Size of the image:  474 640


In [3]:
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
print(gray)

while True:
    cv2.imshow("Original", image)
    cv2.imshow("Gray", gray)
 
    key = cv2.waitKey(1)
    if key == 27:
        break
cv2.destroyAllWindows()

[[180 180 180 ... 172 166 135]
 [180 180 180 ... 169  96  22]
 [179 179 179 ...  92  34  19]
 ...
 [ 90  97 104 ...  44  44  44]
 [ 85  85  82 ...  45  45  47]
 [ 99  96  90 ...  45  45  47]]


In [5]:
from scipy.ndimage import convolve

# let's calculate convolution using kernel

# identity
kernel = [[0, 0, 0], [0, 1, 0], [0, 0, 0]]

# edge detection kernel
kernel = [[0, -1, 0], [-1, 4, -1], [0, -1, 0]]
# or
#kernel = [[-1, -1, -1], [-1, 8, -1], [-1, -1, -1]]

# sharpen kernel
#kernel = [[0, -1, 0], [-1, 5, -1], [0, -1, 0]]

conv = convolve(gray, kernel)
print(conv)

while True:
    cv2.imshow("Original", image)
    cv2.imshow("Gray", gray)
    cv2.imshow("Convolution", conv)
 
    key = cv2.waitKey(1)
    if key == 27:
        break
cv2.destroyAllWindows()

[[  0   0   0 ...  29  95  82]
 [  1   1   1 ... 217 249  72]
 [255 255 255 ... 132 105 224]
 ...
 [248  10  33 ... 254 254 253]
 [237 236 223 ... 254 255   5]
 [ 17  14   7 ... 253 254   2]]


In [6]:
# more advanced filters

import numpy as np

# sobel x
kernel_sobelx = [[-1, 0, 1], [-2, 0, 2], [-1, 0, +1]]
kernel_sobely = [[1, 2, 1], [0, 0, 0], [-1, -2, -1]]

convx = convolve(gray, kernel_sobelx)
convy = convolve(gray, kernel_sobely)

convx2 = [x**2 for x in convx]
convy2 = [y**2 for y in convy]

sobel = np.sqrt(convx2 + convy2)

sobel_uint8 = np.asarray(sobel, dtype=np.uint8)

while True:
    cv2.imshow("Original", image)
    cv2.imshow("Gray", gray)
    cv2.imshow("Convolution X", convx)
    cv2.imshow("Convolution Y", convy)
    cv2.imshow("Sobel", sobel_uint8)
 
    key = cv2.waitKey(1)
    if key == 27:
        break
cv2.destroyAllWindows()

In [ ]:
def CannyThreshold(val):
    low_threshold = val
    img_blur = cv.blur(src_gray, (3,3))
    detected_edges = cv.Canny(img_blur, low_threshold, low_threshold*ratio, kernel_size)
    mask = detected_edges != 0
    dst = src * (mask[:,:,None].astype(src.dtype))
    cv.imshow(window_name, dst)