# TensorFlow with YaleB dataset

In [1]:
import tensorflow as tf
print("Tensorflow version:", tf.__version__)

Tensorflow version: 2.12.0


## Preparing the dataset

In [3]:
import numpy as np

data_path = "./data/yaleExtB_data.npy" # sets the path to the data folder
X = np.load(data_path)
# data = torch.from_numpy(np.load(data_path))

target_path = "./data/yaleExtB_target.npy"
target = np.load(target_path)

print(X[:-5])
print(target[:-5])

[[ 82.  86.  86. ...  91.  85.  80.]
 [ 96.  99. 107. ...  68.  62.  57.]
 [ 98. 104. 117. ...  35.  34.  33.]
 ...
 [ 28.  32.  38. ...  31.   0.   2.]
 [ 34.  35.  38. ...  16.   2.   0.]
 [  5.   5.   9. ...  36.   1.   0.]]
[ 2.  2.  2. ... 39. 39. 39.]


## Encoding target values with OneHotEncoding

In [4]:
from sklearn.preprocessing import OneHotEncoder

onehot_encoder=OneHotEncoder(sparse_output=False)

reshaped=target.reshape(len(target), 1)

Y=onehot_encoder.fit_transform(reshaped)

print(Y[1:10])

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]]


## Train-test data split

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

## Reducing dimension of data using PCA

In [6]:
from sklearn.decomposition import PCA

# PCA 
nof_prin_components = 400  # PARAMETER for optimisation in expereiments
pca = PCA(n_components=nof_prin_components, whiten=True).fit(X_train)
# applies PCA to the train and test images to calculate the principal components
X_train_pca = pca.transform(X_train) 
X_test_pca = pca.transform(X_test)

## Configuring the model

In [7]:
import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.Dense(400, activation='relu'),
    tf.keras.layers.Dense(500, activation='relu'),
    tf.keras.layers.Dense(30, activation='softmax')
  ])
model

## Compile the model

In [8]:
#'''
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
#'''

'''
optimizer = tf.keras.optimizers.Adam(learning_rate=0.1)
model.compile(loss='mse', optimizer=optimizer, metrics=['accuracy'])
'''

"\noptimizer = tf.keras.optimizers.Adam(learning_rate=0.1)\nmodel.compile(loss='mse', optimizer=optimizer, metrics=['accuracy'])\n"

## Train the model

In [9]:
model.fit(X_train_pca, y_train, batch_size=64, epochs=16)

Epoch 1/16
16/16 [==============================] - 0s 3ms/step - loss: 3.0502 - accuracy: 0.2498
Epoch 2/16
16/16 [==============================] - 0s 4ms/step - loss: 0.9090 - accuracy: 0.9602
Epoch 3/16
16/16 [==============================] - 0s 3ms/step - loss: 0.1455 - accuracy: 0.9990
Epoch 4/16
16/16 [==============================] - 0s 3ms/step - loss: 0.0388 - accuracy: 1.0000
Epoch 5/16
16/16 [==============================] - 0s 3ms/step - loss: 0.0132 - accuracy: 1.0000
Epoch 6/16
16/16 [==============================] - 0s 3ms/step - loss: 0.0053 - accuracy: 1.0000
Epoch 7/16
16/16 [==============================] - 0s 3ms/step - loss: 0.0026 - accuracy: 1.0000
Epoch 8/16
16/16 [==============================] - 0s 3ms/step - loss: 0.0016 - accuracy: 1.0000
Epoch 9/16
16/16 [==============================] - 0s 2ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 10/16
16/16 [==============================] - 0s 2ms/step - loss: 8.7571e-04 - accuracy: 1.0000
Epoch 11/16
16/

## Evaluation of the model with test data

In [10]:
loss, accuracy = model.evaluate(X_test_pca, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.19094914197921753
Test accuracy: 0.9414141178131104


## Predicting the output

In [11]:
y_pred = model.predict(X_test_pca)
y_pred[:5]

16/16 [==============================] - 0s 1ms/step


array([[1.31717734e-05, 4.26180804e-06, 5.29064437e-06, 1.73115095e-05,
        1.71808456e-03, 2.64110513e-05, 1.80847553e-06, 3.87393142e-04,
        2.59638124e-04, 1.18813645e-04, 7.85413606e-04, 1.48255815e-04,
        1.41719618e-04, 1.56220712e-03, 5.71447657e-04, 1.54080899e-05,
        1.22005775e-04, 5.02643350e-04, 9.07196663e-04, 5.29975514e-04,
        2.33534392e-05, 8.51185818e-04, 9.86818194e-01, 5.08338504e-04,
        1.14713766e-04, 1.12886410e-04, 3.47216404e-03, 1.69736486e-05,
        7.32902845e-06, 2.36391235e-04],
       [1.34777329e-05, 1.10954497e-05, 3.49479228e-06, 8.39585300e-06,
        1.59954755e-06, 8.85638747e-06, 1.26599616e-05, 2.04691514e-05,
        6.23445067e-06, 4.37224617e-06, 2.42114729e-05, 8.53413803e-06,
        2.99482308e-05, 7.94979223e-06, 9.93691810e-06, 3.33614007e-05,
        1.04333893e-04, 5.98083607e-05, 3.99921055e-06, 3.42074804e-06,
        1.94142535e-06, 5.39211851e-06, 6.72687238e-05, 6.01034253e-06,
        1.46772232e-04,

## Compare actual and predicted values

In [12]:
import numpy as np
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")

Actual: [22 27  8  8  9 17 21 14 25  5 17 28 14 27  1 25 29 12  8  1 23 22 23 24
 28  8 29 29 24 25 21 12 25 20  4  6  8  8 22  1 27  8 26 17 21  7  7  6
 14 19 12 10 22 25 11 13  0  9  6 18 12 11  9  1 16  9  6 21 24  3  6 17
 15  5 14 26 13 10  9 18 20  0  4 15 16  1 12 18 15 18 22  4  5 28 21  9
  8  2 23  7 19 14 22 21  9  0  1 23  0 17  9 26 14  4  2  8 16  3  2 21
 19 27 28  8  2 24 25 15 24  9 24  1 20 29 11  0  9  7 19  5 23  5 29  4
 11 26 13 20  6 15 27 24 19 29 10 28 23  3  7  0  8  6 20 28  2  2 29 21
 19  7  4 21 10 14  2  4 22 13  9 26  5 11  4  0 26 16 19  7 21 26 11 17
 26 26 18  3 18  5 15  8 19 12  8  9 23 18  3 13  7 17  1 23 15 28  5  6
 24  9 26  3 24 18 14 11  4  9  0  1 24 27 21  8 14 22 20 21 26 24 24 28
 12 21 16  1 10 10 26 23 23 12 20  5 26 12 20 19  7 11 19 23 22  4 11 19
 28 23 11  4 21 17  7  1  6 28 16 25 28 24  7 27 23 26 24 14  4 12  3 25
  1 28 11 23  2 25 15 19 15 25 23 16  7 10 29 22  6  7 29 20 14  6  8 24
  8 12 22 13 13 15  5 21 18 23 13 16 16 29 